### ISSUE TITLE
How to mock variables/methods which are added in src packages

### ISSUE THREAD

**Issue by mioyn** [jenkinsci/JenkinsPipelineUnit#106]
I have a common code in src folder, in package 
com.mycom.utils
File : CommonStages.groovy
Code: 
def execute() {
 stage('some stage') {
   node ('someNode'){
      Println env.someenv
   
   }
}
}

Am getting no signature of method error com.mycom.utils.commonstages.stage()
Is applicable for argument types: (java.lang.String, com.mycom.utils.commonsatges$_execute_closure1) 

If the code is in jenkinsfile it executes but when I add it to the package structure it fails

**Comment by recampbell** [comment]
I wonder if @ozangunalp has any insight here?

**Comment by wololock** [comment]
Try passing a reference to `Script` to `CommonStages` class, something like:

```
class CommonStages {
    def script

    CommonStages(Script script) {
         this.script = script
    }

    def execute() {
        script.stage('some stage') {
            script.node('someNode) {
                println env.someenv
            }
        }
    }
}
```

You get this exception because `CommonStages` class does not extend script that provides step methods like `stage`, `node` and others. You can also try simplifying this code with `@Delegate` annotation which allow you to call `stage` and `node` without `script.`, e.g.

```
class CommonStages {
    @Delegate
    def script

    CommonStages(Script script) {
         this.script = script
    }

    def execute() {
        stage('some stage') {
            node('someNode) {
                println env.someenv
            }
        }
    }
}
```

`@Delegate` delegates execution of methods that don't exist in class to the object annotated with this annotation.

**Comment by mioyn** [comment]
The first approach works but for the other when using `@Delegate` it fails with
       Unsupported expression for CPS transformation @ line -1

**Comment by wololock** [comment]
Seems like Groovy CPS does not support it. I haven't try it inside Jenkins, for some reason my pipelines use the first approach with a success. Thanks for testing both !
