### ISSUE TITLE
Q: Is this project maintained?

### ISSUE THREAD

**Issue by teosoft123** [jenkinsci/JenkinsPipelineUnit#115]
The last commit was 11 month ago. Any decent forks, out of 94? Is any of them becoming "official" and maintained implementation of this framework?

**Comment by mkobit** [comment]
If it is not, I believe that there is a way to request/transfer ownership since it is under the `jenkinsci` umbrella if somebody else is willing to take control.

**Comment by ozangunalp** [comment]
Hey @teosoft123 @mkobit 

You are right, I didn't had much time last year to maintain the project actively. 
I'll take a couple of actions to keep the project more usable : 
- a gitter community for people to exchange usage practices.
- sort out open issues and classify them, answer a couple of 
- merge PRs that make sense
- onboard some one to the project to keep the maintenance, probably @stchar

Despite all these I do not think that I'll have time to respond questions very actively.

Lastly I more than anyone else understand your frustration, but I think that your suggestion to transfer the project ownership is absurd. 

Cheers

**Comment by oleg-nenashev** [comment]
"Transferring ownership" in Jenkins project terms usually means "adding
more maintainers". We rarely remove maintainers, only in edge cases.

Generally Jenkins adoption process allows transferring ownership when a
maintainer is unresponsive. It requires a message to the mailing list and
then there is a 2-week timeout (or more if there is evidence that the
maintainer is active).

For the record, I tried to reach out to Ozan few times over last months +
Kohsuke contacted Ozan in Paris in June and got his response that Ozan is
still interested. So I didn't consider ownership transfer without Ozan's
response at this stage.

Anyway, it is great to see that there are going to be more maintainers.


On Aug 6, 2018 21:58, "ozangunalp" <notifications@github.com> wrote:

Hey @teosoft123 <https://github.com/teosoft123> @mkobit
<https://github.com/mkobit>

You are right, I didn't had much time last year to maintain the project
actively.
I'll take a couple of actions to keep the project more usable :

   - a gitter community for people to exchange usage practices.
   - sort out open issues and classify them, answer a couple of
   - merge PRs that make sense
   - onboard some one to the project to keep the maintenance, probably
   @stchar <https://github.com/stchar>

Despite all these I do not think that I'll have time to respond questions
very actively.

Lastly I more than anyone else understand your frustration, but I think
that your suggestion to transfer the project ownership is absurd.

Cheers

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jenkinsci/JenkinsPipelineUnit/issues/115#issuecomment-410834312>,
or mute the thread

**Comment by mkobit** [comment]
Thanks @ozangunalp for the response. Sorry if I came off as accusatory or offensive, I did not intend to. I mainly wanted to point out that if indeed the project was unmaintained/dead, that the Jenkins organization have processes in place for transferring ownership. This being an alternative compared to some other open source projects which require forking and possibly leading to fragmentation (for example,  what happened to https://github.com/findbugsproject/findbugs ).

**Comment by oleg-nenashev** [comment]
Oh, my email got really messed up. Will edit

**Comment by ozangunalp** [comment]
Thanks for details Oleg

@mkobit none taken. I understand very well. I also want that the project to continue to serve the community.

**Comment by hypery2k** [comment]
@ozangunalp Did you need help on supporting this project? Would be glad on help. I already maintaining a jenkins plugin and gladly to help improving this project, e.g checking PRs and further development, e.g code coverage additions ....

**Comment by macg33zr** [comment]
@ozangunalp @oleg-nenashev I also may be able to help maintaining this project - I should have more free time in coming months. I have used this quite a lot in testing Jenkins automation projects where I work. I wrote my own wrapper project for it to use with Spock and Declarative pipelines, which may give some ideas for enhancements. I have not done much open source work though - mostly closed source and consuming OSS..I would like to give back!

**Comment by Zougi** [comment]
It's great qualified people volunteered to maintain this project, and give it a future! @macg33zr I appreciate your shared work on showing how to make this framework work with spock!
@OliverNocon could people from [SAP/jenkins-library](https://github.com/SAP/jenkins-library) be interested? Piper team is not the only one making shared libraries within SAP. Merging some of the team's work within JenkinsPipelineUnit would make it easier to reuse for everyone.

**Comment by hypery2k** [comment]
should we schedule a hangout for discussion or a slack?

**Comment by ozangunalp** [comment]
@Zougi I'll check out the SAP/jenkins-library. It'll be great to see how people are using/extending the FW and backport some of it into the JPU.

@hypery2k I'd suggest having the discussion on https://gitter.im/JenkinsPipelineUnit

**Comment by OliverNocon** [comment]
I am happy to assist and provide more details about what we did in [SAP/jenkins-library](https://github.com/SAP/jenkins-library).

Main things we invested in were:

* improve performance (avoid library loading/initialization per test). We introduced a new base class for our tests (https://github.com/SAP/jenkins-library/blob/master/test/groovy/util/BasePiperTest.groovy).
* add rules (e.g. https://github.com/SAP/jenkins-library/blob/master/test/groovy/util/JenkinsShellCallRule.groovy) to optimize writing tests

**Comment by ianfixes** [comment]
What sort of timeline are we talking about here?  And what would be the MVP for making the project more maintainable by others?  

In the frameworks I've written in the past, it has helped to bundle an example project with the library -- it demonstrates the usage of the library as well as (via CI) ensuring that it actually works in practice. That seems like it would provide a huge boost in confidence when judging all the open pull requests.

I don't see an example project here, and none of the examples I've found (https://github.com/jimcroft/jenkinslib-example being the most credible) seem 100% functional.  If I take on that task, is there someone here that could provide guidance on my pull request?

**Comment by stchar** [comment]
Hi, all,  @ozangunalp granted me with permissions to maintain the project. 
I marked some PRs to be released at the first drop, mostly to verify that I have all required perms to act as maintainer.

If you have anything to discuss please ping me in the gitter channel https://gitter.im/JenkinsPipelineUnit/Lobby

**Comment by stchar** [comment]
Integratted some PRs, now you can send a request to jenkinsci to get the access to the repo.
