### ISSUE TITLE
Unable to run 'git' command

### ISSUE THREAD

**Issue by mokes2020** [jenkinsci/JenkinsPipelineUnit#233]
I tried adding 'git' under 'helper.registerAllowedMethod', but still getting the following error when running the unit test.
java.lang.NullPointerException: Cannot get property 'git' on null object

**Comment by nre-ableton** [comment]
Can you please post a code snippet showing how and where are you calling `registerAllowedMethod`?

**Comment by mokes2020** [comment]
This is called under void mockMethods() 
helper.registerAllowedMethod("git", [String.class], null)

**Comment by nre-ableton** [comment]
As far as I can tell, the `git` pipeline step doesn't take a string as its argument, it takes a map. So you'd need to do this instead:

```groovy
 helper.registerAllowedMethod("git", [Map], null)
```

**Comment by stchar** [comment]
@mokes2020,

helper.registerAllowedMethod("git", [Map], null) lets you to use following snippet in your pipeline or shared library
```
git url: "https://github.com/jenkinsci/JenkinsPipelineUnit.git" branch: "some-branch"
```

helper.registerAllowedMethod("git", [String], null)
```
git "https://github.com/jenkinsci/JenkinsPipelineUnit.git"
```

In order to help you we need to see your:
1.  Pipeline/shared library
2. Test
3. Stacktrace 

If sharing the sources is not applicable try to reproduce your error on a "hello world" application and share it here

**Comment by stchar** [comment]
@mokes2020, I believe this could be closed, hope we've managed to help. please re-open if you have further questions.
