### ISSUE TITLE
Use addShMock for sh with parameters

### ISSUE THREAD

**Issue by ruslan-k** [jenkinsci/JenkinsPipelineUnit#378]
Hello. I am having issue with addShMock with sh that contains parameters.

For example, if sh looks like this:
sh(returnStdout: true, script:  "echo '${some_param}'")
This mock does not work:
helper.addShMock("echo '\\${some_param}'", "Success", 0)
and this does not work either:
helper.addShMock('echo \\'${some_param}\\'', "Success", 0)

Is there any workaround to resolve this problem?

**Comment by nre-ableton** [comment]
The problem is that variable interpolation will happen at the point where the mock is added, not during runtime. So for example:

```groovy
    String hello = 'foo'
    script.sh("echo '${hello}'")
```

...in order to mock the above code, you need to do this:

```groovy
    helper.addShMock('echo \'foo\'', 'Success', 0)
```

You can't call this as `helper.addShMock('echo \'${hello}\'', '', 0)`, because by the time the `sh` mock receives the call, the variable has already been interpolated.

**Comment by ruslan-k** [comment]
Thanks a lot, this worked
