### ISSUE TITLE
Can this framework be used with custom step and is it possible to get access to all the default mocks for them?

### ISSUE THREAD

**Issue by red8888** [jenkinsci/JenkinsPipelineUnit#397]
I have a number of custom steps I use in my pipelines: https://www.jenkins.io/doc/book/pipeline/shared-libraries/#defining-custom-steps

I want to unit test them but can't figure out if this framework can help with that. 

I can call the actual groovy script in unit tests like this which would work well enough for me:

```
   # vars/myCustomStep.grooy
   def call(Map config) {
     def paramOne = config.paramOne
     echo deployment
    
   }

    # my unit test
    def myCustomStep = new GroovyShell().parse( new File( 'vars/myCustomStep.groovy' ) )
    myCustomStep paramOne: "sdlfsdfdsf"
```

But my custom steps use jenkins steps like `echo` `container{}` etc. This framework already has all of those mocked and I want to take advantage of it- otherwise for my custom steps I need to manually mock ALL the jenkins steps/plugins im using.

I want to get access to all these pre-mocked methods: https://github.com/jenkinsci/JenkinsPipelineUnit/blob/2ad9665d0d6f9d1d81332d3af3dad42cf985edba/src/main/groovy/com/lesfurets/jenkins/unit/BasePipelineTest.groovy#L111

For example this doesnt work but something like this where I could call `registerAllowedMethods()` 
```
    # Some way I can access the mocks manually?
    def helper = new PipelineTestHelper()
    def echo = { println 'withoutArgs' }
    helper.registerAllowedMethod('withoutArgs', echo)
    # I still get "No signature of method: myCustomStep.echo()"
    def myCustomStep = new GroovyShell().parse( new File( 'vars/myCustomStep.groovy' ) )
    myCustomStep paramOne: "sdlfsdfdsf"
```

**Comment by nre-ableton** [comment]
I think that using `new GroovyShell().parse( new File( 'vars/myCustomStep.groovy' ) )` is not the way to go.

First of all, I don't recommend testing singletons (aka custom steps) like this directly. It will make things complicated once you have dependencies on other singletons etc. Usually I structure pipeline libraries like so:

```
.
├── src
│   └── com
│       └── companyname
├── test
│   ├── com
│   │   └── companyname
│   └── resources
└── vars
```

The actual work is done in classes under `src`, for example:

```groovy
// src/com/companyname/Foo.groovy
package com.companyname

class Foo implements Serializable {
  Object script = null

  String bar() {
    script.echo 'hello from bar'
    return 'bar'
  }
}
```

The corresponding singleton would look like this:

```groovy
// vars/foo.groovy
import com.companyname.Foo

String bar() {
  return new Foo(script: this).bar()
}
```

The corresponding test case looks like:

```groovy
// test/com/companyname/FooTest.groovy
package com.companyname

import static org.junit.Assert.assertEquals

import com.lesfurets.jenkins.unit.BasePipelineTest
import org.junit.Before
import org.junit.Test

class FooTest extends BasePipelineTest {
  Object script = null

  @Override
  @Setup
  void setUp() {
    super.setUp()
    this.script = loadScript('test/resources/EmptyPipeline.groovy') // a file with just "return this"
  }

  @Test
  void testBar() {
    assertEquals('bar', new Foo(script: script).bar())
  }
}
```

I realize that you may not want to restructure your project like this, but again, it makes more sense when your project starts to grow in size and complexity. Anyways, with your current structure you can still test the singleton, but you'll need to do it like this:

```groovy
// test/fooTest.groovy
@SuppressWarnings('ClassName')
class fooTest extends BasePipelineTest {
  Object foo

  @Override
  @Before
  void setUp() {
    super.setUp()
    this.foo = new foo()
    foo.echo = { i - > println(i) }
  }
```

Unfortunately, you can't access registered methods on `PipelineTestHelper`, because they are stored in a protected field. This isn't too bad when you have just a few mocks to deal with, but based on your question, it seems that you may have more. So the structure that I suggest might end up saving you time in the end.

Hope that this helps!

**Comment by red8888** [comment]
Thanks for replying! I like this idea, but I have some issues with it (that I might be wrong about)

One of my concerns with the pattern your using is the potential load it might put on the master. We already make heavy use of logic outside the pipeline directive and use  `script{}` quite a bit and it seems to be ok, but I worry about passing literally everything through src code. Cloudbees generally advises against this (they take an even more uncompromising stance) because all that code is processed on the master NOT on the build nodes which is where you want all the heavy lifting to happen.

Unless all your code in src is just returning strings to pass the sh step in vars scripts? 

What about stuff that uses plugins? Are you referencing plugin methods inside src too?

Thanks!

**Comment by nre-ableton** [comment]
Regarding load, so far it hasn't been a problem for us. Our Jenkins cluster is around 70 nodes at the moment (plus 32 executors on the controller). We prevent actual jobs from executing on the controller, so it basically only processes Jenkinsfiles. Our controller is a rather modest 4-core VM, which is rarely at capacity with respect to CPU usage. Here's a quick graph from one of our monitoring dashboards for a somewhat high-load workday:

![Screenshot from 2021-09-15 19-18-30](https://user-images.githubusercontent.com/16208985/133479749-756657d5-544d-4415-9f4a-3921c958538d.png)

Basically, the CPU usage for munging around a bit of Groovy data pales in comparison to building our actual software on the build nodes. :smile: However, it's worth noting that we've taken a pedantic and highly-testable approach to building pipeline libraries, and worry about performance later. That's not to say we are tolerant of inefficient code, but we feel that the performance overhead of well-structured code is a (usually small) price worth paying. For your organization and needs, this approach may not necessarily make sense. In other words, YMMV.

Where does Cloudbees specifically advise against creating classes in `src`? I would be interested to see their argument.

And yes, we do occasionally reference plugin methods from our pipeline libraries. Note that you need to use the `script` context for any plugin method or Jenkins pipeline API.

**Comment by red8888** [comment]
Wow great info! Yeah we have a single master and I'd like to keep it that way for simplicity so this is always a concern for me.

 Cloudbees tries to steer you away from using practically any raw code and use declarative syntax at all times- they of course have zero to say about unit testing.

So your calling `script{}` inside of code in `src`? For some reason I thought that wasn't possible. I thought you could only use like non jenkins methods in src. can you call the `sh` step in src code and those kinds of methods?

**Comment by nre-ableton** [comment]
Ah, I see. We don't use the declarative syntax at all, only scripted pipelines. Our developers prefer scripted pipelines because they resemble normal code and don't have as much of a learning curve. They are much easier to debug and also you get nice code completion and hinting when using IDEs like IntelliJ. Also, we find the deep indentation levels common in the declarative API to be annoying. Also, when we started writing pipelines for most of our jobs, the declarative API didn't have good support for parallelism (which is essential for us, since we build on several platforms simultaneously). That has since been improved, from what I understand, but we don't have any interest in the declarative API for the other reasons mentioned.

I think there is some misunderstanding here -- since we don't use the declarative API, I'm not referring to the `script` block. I'm referring to the script context. So imagine a pipeline that _just_ contains `return this` in the body. The `this` object, which is actually an instance of `WorkflowScript` (IIRC) is what I'm referring to with the script context. All pipeline API methods, such as `sh`, `echo`, `node`, `stage`, etc., need a script context. Since a Jenkinsfile is initialized by Jenkins at runtime to be an instance of `WorkflowScript`, you can call such methods normally (same goes for pipeline library singletons, ie `vars/foo.groovy`). But for other classes, they need to be provided a script context to access these API calls. This is one of the reasons that we find this architecture to be preferable, since it allows one to easily inject a mocked script context when testing classes.

**Comment by nre-ableton** [comment]
BTW, if you want to see a real-world example of this architecture, here's one of the pipeline libraries that my company has open-sourced: https://github.com/Ableton/python-pipeline-utils . Hope you find this useful!

**Comment by red8888** [comment]
Thanks that is helpful.
