### ISSUE TITLE
Add Linux and OSX to CI

### ISSUE THREAD

**Issue by dblock** [jenkinsci/JenkinsPipelineUnit#424]
### Feature Request

Run tests on Linux and MacOS, useful for ensuring things like #423 don’t happen.

Could easily get rid of AppVeyor for GHA. I can PR on top of https://github.com/dblock/JenkinsPipelineUnit/commit/a648c246a63e0e899ebd70c0972a5f259e0ce17d If there’s interest

**Comment by nre-ableton** [comment]
I'm not a huge fan of Travis, so I'm not opposed to changing the CI to something else. However, I'm not the owner of this repo and the decision is not mine to make. It would probably be worth exploring whether the Jenkins organization has a general recommendation on CI infrastructure.

**Comment by dblock** [comment]
Not a fan of Travis either. I mean GitHub actions.

**Comment by nre-ableton** [comment]
I asked around a bit on gittr's jenkinsci room what CI we should use, and while they agreed that GitHub Actions was preferable to AppVeyor/Travis, it was recommended that we use the [jenkinsci Jenkins instance](https://ci.jenkins.io/). There's already a Jenkinsfile in the repo, so it seems that someone set this up in the past. However, I couldn't find any previous builds, so I'm not sure what's going on... I'll look into this to see if there's an easy way to get our project building there.

Regardless, since this is a Jenkins-based framework, it seems that testing on Jenkins would indeed be more logical than other CI providers.

**Comment by dblock** [comment]
No hard feelings about which CI we use @nre-ableton! My preference has always been GHA because it's zero-setup, but if we can get all platforms on jenkins-ci, great.

**Comment by nre-ableton** [comment]
Although GitHub actions are convenient, we'd like to try and get Jenkins working if possible. The Jenkins infrastructure team [reached out to us](https://github.com/jenkinsci/JenkinsPipelineUnit/pull/482#issuecomment-1033924604), and suggested we file an issue, which I have done here: https://github.com/jenkins-infra/helpdesk/issues/2776.

**Comment by nre-ableton** [comment]
We will add Linux and replace Windows in #486. Mac support will be provided via GitHub actions. I'll make a PR based on #425 for that.
