### ISSUE TITLE
Upgrade dependencies to remediate CVEs

### ISSUE THREAD

**Issue by dblock** [jenkinsci/JenkinsPipelineUnit#436]
### Feature Request

We have discussed locking things like Groovy in https://github.com/jenkinsci/JenkinsPipelineUnit/pull/426#issuecomment-966507392 to as close as possible to Jenkins. 

One drawback is that CVE scanning is all over the place for these dependencies. See https://github.com/opensearch-project/opensearch-build/issues?q=is%3Aissue+is%3Aopen+label%3A%22security+vulnerability%22 for a list. What can/should we upgrade?

**Comment by nre-ableton** [comment]
We should probably use dependabot to keep our dependencies updated.

**Comment by dblock** [comment]
We *are* bringing a much older version of jenkins-core, so dependabot is probably not enough.

**Comment by nre-ableton** [comment]
@dblock Where is that dependency defined? I don't see it in `build.gradle`, so I presume it's a dependency of one of our direct dependencies?

**Comment by dblock** [comment]
> @dblock Where is that dependency defined? I don't see it in `build.gradle`, so I presume it's a dependency of one of our direct dependencies?

Honestly I don't know and haven't dug into it (could use some help). I got a project using JenkinsPipelineUnit that is bright red and I'd like to fix that without forcing version of transitive dependencies.

**Comment by nre-ableton** [comment]
@dblock I'm reopening the issue, since I don't like long discussions on closed issues. :smile: 

That said, a bit of googling revealed that there is a `gradle dependecies` command, which generated this: 
[dependencies.txt](https://github.com/jenkinsci/JenkinsPipelineUnit/files/7806957/dependencies.txt)

I don't see jenkins-core in there anywhere, so I am actually wondering if JenkinsPipelineUnit is indeed the cause of this error for you. Can you provide any other information about the warnings you are seeing?

**Comment by dblock** [comment]
This was my bad to say that it came from here - we just use an older jenkins shared library dependency. See https://github.com/opensearch-project/opensearch-build/pull/1425 for a fix. Thanks for your help @nre-ableton!

**Comment by nre-ableton** [comment]
@dblock Ok, glad that there was a reasonable explanation! And on the plus side, you opening this issue forced us to finally get around to adding dependabot support to the repo, so everything is now in a better state than when we started. :slightly_smiling_face:
