### ISSUE TITLE
Support for mocking Windows `cmd` shell

### ISSUE THREAD

**Issue by UlrichEckhardt** [jenkinsci/JenkinsPipelineUnit#481]
### What feature do you want to see added?

There is extensive support for mocking `sh()` calls. I'd like to have the same for `bat()` calls.

One problem with this that I can already foresee comes from replacing this:
```
        helper.registerAllowedMethod('bat', [Map.class], {m->
            if(m.returnStdout){
                return """uno-dos@localhost> "${m.script}"\r\naaa\r\nbbb\r\nccc"""
            }
            return null
        })
```
Here, you have some default mocked behaviour that some code may rely on.

Currently, as a workaround, I'm using this setup code:
```
        // redirect `bat()` to the `sh()` support code
        // Windows `cmd` shell is not specially supported by the framework
        // but handled like just any call. We redirect it to the code used
        // for `sh` in order to get better configurable mocking support.
        this.helper.registerAllowedMethod('bat', [String], { args -> helper.runSh(args) })
        this.helper.registerAllowedMethod('bat', [Map], { args -> helper.runSh(args) })
```
and then use `helper.addShMock(...)` to customize the `bat()` mock behaviour.

I'm willing to create a pull request, but I have a few questions up front:

- Would there be interest at all?
- Should I simply adjust code so that above workaround is implemented automatically? The alternative would be to duplicate the infrastructure provided by the helper class, so that you then get `helper.addBatMock()` and `helper.runBat()`.

**Comment by nre-ableton** [comment]
So yeah, the default mocked output for `sh` used to be similar as the one for `bat`, but it was removed in [d93ec15](https://github.com/jenkinsci/JenkinsPipelineUnit/commit/d93ec155c54dd029632ee9bf881a9ef65e15636e#diff-6b8b54b45028e711007bd6db85927c3fbd124f06b62369c9aedd515bfa4e8198L181-L185). IMHO, that default output was not useful at all and can easily be removed. However, doing so will require us to document a breaking change in the release notes for the next version. Not a big deal, but we just need to notify users of the breaking API change so there aren't any surprises during updates.

In regards to your other questions:

1. I'm not sure. I mean, my [company](https://www.ableton.com/) tests extensively on Windows and although we have a lot of Jenkinsfiles on that platform, we actually don't use `bat` because `sh` works fine for us (since it is provided by git for Windows). But if you have a use-case for `bat`, that's good enough for me. :smile: Although this isn't stated explicitly in the docs, the goal of this project should be to provide good mocks for all built-in pipeline steps, and `bat` is definitely included in that. So yes, a PR would be welcome and I'd be happy to review/merge it, so you can add me as a reviewer if you get around to submitting it.
2. Your workaround looks fine to me. I would simply replace the `bat` mocks in `BasePipelineTest` [here](https://github.com/jenkinsci/JenkinsPipelineUnit/blob/b380937f648bc1c15de5fb61361fe2c835fdbeff/src/main/groovy/com/lesfurets/jenkins/unit/BasePipelineTest.groovy#L132-L138) with calls to `runSh` as you suggest. You might also need to tweak the tests a bit.

**Comment by nre-ableton** [comment]
@UlrichEckhardt sounds good. I don't have time to look at your branch right now, but when you are ready to submit a PR, you can click the "allow edits from maintainers" box and I can push fixups to your branch.
