### ISSUE TITLE
Support environment variable that are not of String type

### ISSUE THREAD

**Issue by dduportal** [jenkinsci/JenkinsPipelineUnit#494]
### What feature do you want to see added?

The branch API plugin introduced a new environment variable named `BRANCH_IS_PRIMARY` in https://github.com/jenkinsci/branch-api-plugin/releases/tag/branch-api-2.6.4.

While trying to use this variables in https://github.com/jenkins-infra/pipeline-library, we stumbled across the fact that we can only simulate environment variable of type `String` as per the `addEnvVar()` signature: https://github.com/jenkinsci/JenkinsPipelineUnit/blob/d176fa1039fa23b9f423fa1eb9d601d0ddb1a064/src/main/groovy/com/lesfurets/jenkins/unit/BasePipelineTest.groovy#L498.

It makes it trickier to correctly test since the instruction `if (env.BRANCH_IS_PRIMARY)` returns true if we test a case where `addEnvVar('BRANCH_IS_PRIMARY', 'false') `, because with the groovy behavior, a non empty string means "true".

The authors of this pipeline features discussed about that in https://github.com/jenkinsci/branch-api-plugin/pull/246: generally, the variable isn't set unless true to be "safe": our test cases are assuming the same to work as expected.

But to make this fraemwork easier to use (avoid this kind of tricky error to bite users),  WDYT about supporting any kind of object type (not only string) for the method `addEnvVar()`, like it's done with `addParam()`?

I'm willing to contribute this change but I want a go/no go before spending time on it, because I might have misunderstood it or it could break other usages that I'm not aware of.

### Upstream changes

- https://github.com/jenkinsci/branch-api-plugin/releases/tag/branch-api-2.6.4
- https://github.com/jenkinsci/branch-api-plugin/pull/246
- https://github.com/jenkins-infra/pipeline-library

**Comment by UlrichEckhardt** [comment]
The possible values for environment variables is not defined by the code here. This code only represents what the underlying OSs support (they define and manage the actual environment variables). For that reason, it's string (actually, I believe, not even all strings, only those without embedded NUL characters) or null (meaning "not defined").
The comparison with `addParam()` doesn't apply, because that is fully implemented in Groovy code.

In any case, if you make your pipeline depend on this env var, that's a perfect case to use unit testing to ensure that your code handles all of `null`, `'true'`, `'false'` correctly.

**Comment by dduportal** [comment]
Thanks for the explanation. I'm closing the PR as it make sense, even if I feel that the `env.` object is pure groovy so it could help beginners.
But your argument for unit testing this case is a good and important one!
