### ISSUE TITLE
Test Regression - git rev-parse HEAD no longer returns a value

### ISSUE THREAD

**Issue by marblenix** [jenkinsci/JenkinsPipelineUnit#523]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  N/A
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

1. Follow setup in JenkinsPipelineUnit/README
2. Set the verison of `jenkins-pipeline-unit` to 1.10
3. Write a new test that matches:
```groovy
@Test
void testGit() {
    def result = script.sh("git rev-parse HEAD")
    assertEquals("\nbbb\nccc\n", result)
}
```
4. see that the test passes
5. update `jenkins-pipeline-unit` to 1.14
6. see that the test fails

### Expected Results

The tests continue to pass

### Actual Results

The tests fail

### Anything else?

See pull request https://github.com/jenkinsci/JenkinsPipelineUnit/pull/483

I found an easy workaround, but I made the issue anyway to help with documentation and to help anyone else that saw their tests suddenly fail.

Workaround:
```groovy
@Test
void testGit() {
    helper.addShMock("git rev-parse HEAD", "\nbbb\nccc\n", 0)
    def result = script.sh(script: "git rev-parse HEAD", returnStdout: true)
    assertEquals("\nbbb\nccc\n", result)
}
```

**Comment by nre-ableton** [comment]
This API breakage was clearly documented in the [release notes](https://github.com/jenkinsci/JenkinsPipelineUnit/releases/tag/v1.14) for version 1.14, and the removal of this mock was intentional because of other refactorings and improvements that have been made recently with `addShMock`.

But thanks for posting a workaround; our documentation just linked to the documentation on `addShMock`, but it's nice to have an explicit example for others who may stumble across this problem in the future. 👍
