### ISSUE TITLE
Jenkins Pipeline Unit test doesn't pick up ansiColor plugin 

### ISSUE THREAD

**Issue by shinhf** [jenkinsci/JenkinsPipelineUnit#540]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.263.4
OS: Linux - 4.4.0-142-generic

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

I'm running tests on MacOS

### Reproduction steps

I'm trying to test simple Jenkinsfile Pipeline using Jenkins Pipeline Unit and I have an issue with plugin ansiColor.

1) I added plugin to build.gradle file:

`dependencies { [...] testImplementation 'org.jenkins-ci.plugins:ansicolor:1.0.0' }`

2) I added option to Jenkinsfile

`pipeline { options { ansiColor('xterm') [...] }`

3) After running "gradle clean test" I received an error:

```
  Test testExamplePipeline FAILED (2.2s)
  groovy.lang.MissingMethodException: No signature of method: Jenkinsfile.ansiColor() is applicable for argument types: (String) values: [xterm]
      at app//TestExampleJenkinsfile.testExamplePipeline(TestExampleJenkinsfile.groovy:16)

How to correctly add plugin to Jenkins Pipeline Unit test?
```

PS: Code is available here: https://github.com/shinhf/jenkins-jpu-test-example

PS2 I know I can always register method using registerAllowedMethod, but I think it's not resolution:

`helper.registerAllowedMethod("ansiColor", [String], null)`

### Expected Results

Test would be completed successfully

### Actual Results

  Test testExamplePipeline FAILED (2.2s)
  groovy.lang.MissingMethodException: No signature of method: Jenkinsfile.ansiColor() is applicable for argument types: (String) values: [xterm]
      at app//TestExampleJenkinsfile.testExamplePipeline(TestExampleJenkinsfile.groovy:16)

**Comment by nre-ableton** [comment]
Yes, as you suggested, you can indeed register a mock for the `ansiColor` step in your test class' `setUp` method (or even on a per-test bases), and that _is_ the best solution in this case.

This project provides out-of-the-box mocks for the basic pipeline steps (which was completed as of https://github.com/jenkinsci/JenkinsPipelineUnit/pull/518), but no other plugins, with the exception of the `docker-workflow` plugin because it is very widely used. We don't want to provide mocks for tons of other Jenkins plugins, because that will result in lots of outdated and unmaintained code. So unfortunately, I'm closing this issue as "wontfix".
