### ISSUE TITLE
How to mock Jenkins commands (like steps.stash) to test shared library

### ISSUE THREAD

**Issue by ghost** [jenkinsci/JenkinsPipelineUnit#62]
Hi,
I am using JenkinsPipelineUtil to tests our library. I am not having success to mock Jenkins commands like steps.stash or steps.unstash

This is an other example of testing our library step
def call(Map parameters = [:]) {
    handleStepErrors (stepName: '_aTest', stepParameters: parameters) {
        def script = parameters.script
       def response = script.httpRequest httpMode: 'GET', authentication: parameters.credentials, url: parameters.url
        def delivery = script.readJSON text: response.content
        def result = delivery[0].DELIVERY_EXT_GUID
        echo result
        steps.stash result
    }
}

Here I am not able to mock  script.httpRequest, script.readJSON and steps.stash
Could you please advise how to mock this?
Thank you very much in advance.

**Comment by headcrabmeat** [comment]
is it still actual?

**Comment by jgiovaresco** [comment]
@barlogy 

To mock `httpRequest` I've just did

```
helper.registerAllowedMethod(
    method("httpRequest", Map.class),
    { _ -> ["content": "{}"] }
)
```

It's working but I don't know if there is a better way

**Comment by gene-pavlovsky** [comment]
In my test, I needed to mock `readJSON`. Well, it's not fully a mock, since it does actually parse the JSON.
`        helper.registerAllowedMethod('readJSON', [Map], { req -> new groovy.json.JsonSlurper().parseText(req.text) })`

**Comment by jcrben** [comment]
Can this library provide default mocks? For readJSON something that actually reads JSON like the above would be a nice default.

**Comment by nre-ableton** [comment]
@jcrben This library provides default mocks for all basic pipeline steps (which was finalized in https://github.com/jenkinsci/JenkinsPipelineUnit/pull/518). However, as the `readJSON` step is part of a plugin (`pipeline-utility-steps`), there is no default mock for it and you must create your own as @gene-pavlovsky detailed above.

Generally speaking, I don't think that this library should provide default mocks for anything other than the basic pipeline steps, or else it'll be a slippery slope and [`BasePipelineTest`](https://github.com/jenkinsci/JenkinsPipelineUnit/blob/master/src/main/groovy/com/lesfurets/jenkins/unit/BasePipelineTest.groovy) will get bloated.

There is one notable exception to this policy, which is for the `docker-workflow` plugin, because its mocks are somewhat complex and also because it is very widely-used.
