### ISSUE TITLE
MethodSignature.equals fails to account for varargs

### ISSUE THREAD

**Issue by LLCoolDave** [jenkinsci/JenkinsPipelineUnit#79]
Setup: Create shared library with a custom step with a single call signature using a varargs argument, then register and load the library and attempt to use the step from Jenkinsfile in a Test.

Expected Behavior: Call is routed to library.

Actual Behavior: Call is not recognized as an allowed method access as MethodSignature.equals fails to map the signature of the loaded library step to the call signature from the Jenkinsfile.

At first glance it seems that getNativeParameterTypes condenses the varargs to an array argument, at which point the information about the function signature containing a varargs parameter seems to be lost, so the current setup could not even distinguish between a (T[] args) and (T ... args) signature for proper handling inside MethodSignature.equals.

**Comment by stchar** [comment]
> Create shared library with a custom step with a single call signature using a varargs argument, 
https://github.com/jenkinsci/JenkinsPipelineUnit/blob/master/src/test/resources/libs/commons%40master/vars/sayHello.groovy

> then register and load the library and attempt to use the step from Jenkinsfile in a Test
* test scenario
https://github.com/jenkinsci/JenkinsPipelineUnit/blob/912fb118a1cd27feb59d7e12feee40888f7c1006/src/test/groovy/com/lesfurets/jenkins/TestSharedLibraryWithLocalSourceRetriever.groovy#L47

* Register library and run the script it consumes, 
https://github.com/jenkinsci/JenkinsPipelineUnit/blob/912fb118a1cd27feb59d7e12feee40888f7c1006/src/test/groovy/com/lesfurets/jenkins/TestSharedLibraryWithLocalSourceRetriever.groovy#L77

The consumer script calls a method from vars
https://github.com/jenkinsci/JenkinsPipelineUnit/blob/912fb118a1cd27feb59d7e12feee40888f7c1006/src/test/jenkins/job/library/libraryJob.jenkins#L18
> Expected Behavior: Call is routed to library.
I looks like it works

Could you please submit a pull-request with a test case as it not quite clear what the issue is.
